INSERT INTO Clubes(ID,Nombre,NombreLargo,Direccion1,Direccion2,Provincia,Pais,Contacto1,Contacto2,Contacto3,GPS,Web,Email,Facebook,Google,Twitter,Logo,Federations,Observaciones,Baja) VALUES
(2,'L\'Almozara','','Camino de Pinseque, 147-A','50190 Garrapinillos (Zaragoza)','-- Sin Asignar --','ES',' + 34 637 54 15 86','','','','','','','','','almozara.png',1,'',0),
(3,'Afghanistan','','','','-- Sin asignar --','AF','','','','','','','','','','../../server/i18n/AF.png',1,'',0),
(4,'Albania','','','','-- Sin asignar --','AL','','','','','','','','','','../../server/i18n/AL.png',1,'',0),
(5,'Algeria','','','','-- Sin asignar --','DZ','','','','','','','','','','../../server/i18n/DZ.png',1,'',0),
(6,'American Samoa','','','','-- Sin asignar --','AS','','','','','','','','','','../../server/i18n/AS.png',1,'',0),
(7,'Andorra','','','','-- Sin asignar --','AD','','','','','','','','','','../../server/i18n/AD.png',1,'',0),
(8,'Angola','','','','-- Sin asignar --','AO','','','','','','','','','','../../server/i18n/AO.png',1,'',0),
(9,'Anguilla','','','','-- Sin asignar --','AI','','','','','','','','','','../../server/i18n/AI.png',1,'',0),
(10,'Antarctica','','','','-- Sin asignar --','AQ','','','','','','','','','','../../server/i18n/AQ.png',1,'',0),
(11,'Antigua and Barbuda','','','','-- Sin asignar --','AG','','','','','','','','','','../../server/i18n/AG.png',1,'',0),
(12,'Argentina','','','','-- Sin asignar --','AR','','','','','','','','','','../../server/i18n/AR.png',1,'',0),
(13,'Armenia','','','','-- Sin asignar --','AM','','','','','','','','','','../../server/i18n/AM.png',1,'',0),
(14,'Aruba','','','','-- Sin asignar --','AW','','','','','','','','','','../../server/i18n/AW.png',1,'',0),
(15,'Australia','','','','-- Sin asignar --','AU','','','','','','','','','','../../server/i18n/AU.png',1,'',0),
(16,'Austria','','','','-- Sin asignar --','AT','','','','','','','','','','../../server/i18n/AT.png',1,'',0),
(17,'Azerbaijan','','','','-- Sin asignar --','AZ','','','','','','','','','','../../server/i18n/AZ.png',1,'',0),
(18,'Bahamas','','','','-- Sin asignar --','BS','','','','','','','','','','../../server/i18n/BS.png',1,'',0),
(19,'Bahrain','','','','-- Sin asignar --','BH','','','','','','','','','','../../server/i18n/BH.png',1,'',0),
(20,'Bangladesh','','','','-- Sin asignar --','BD','','','','','','','','','','../../server/i18n/BD.png',1,'',0),
(21,'Barbados','','','','-- Sin asignar --','BB','','','','','','','','','','../../server/i18n/BB.png',1,'',0),
(22,'Belarus','','','','-- Sin asignar --','BY','','','','','','','','','','../../server/i18n/BY.png',1,'',0),
(23,'Belgium','','','','-- Sin asignar --','BE','','','','','','','','','','../../server/i18n/BE.png',1,'',0),
(24,'Belize','','','','-- Sin asignar --','BZ','','','','','','','','','','../../server/i18n/BZ.png',1,'',0),
(25,'Benin','','','','-- Sin asignar --','BJ','','','','','','','','','','../../server/i18n/BJ.png',1,'',0),
(26,'Bermuda','','','','-- Sin asignar --','BM','','','','','','','','','','../../server/i18n/BM.png',1,'',0),
(27,'Bhutan','','','','-- Sin asignar --','BT','','','','','','','','','','../../server/i18n/BT.png',1,'',0),
(28,'Bolivia','','','','-- Sin asignar --','BO','','','','','','','','','','../../server/i18n/BO.png',1,'',0),
(29,'Bosnia and Herzegovina','','','','-- Sin asignar --','BA','','','','','','','','','','../../server/i18n/BA.png',1,'',0),
(30,'Botswana','','','','-- Sin asignar --','BW','','','','','','','','','','../../server/i18n/BW.png',1,'',0),
(31,'Bouvet Island','','','','-- Sin asignar --','BV','','','','','','','','','','../../server/i18n/BV.png',1,'',0),
(32,'Brazil','','','','-- Sin asignar --','BR','','','','','','','','','','../../server/i18n/BR.png',1,'',0),
(33,'British Antarctic Territory','','','','-- Sin asignar --','BQ','','','','','','','','','','../../server/i18n/BQ.png',1,'',0),
(34,'British Indian Ocean Territory','','','','-- Sin asignar --','IO','','','','','','','','','','../../server/i18n/IO.png',1,'',0),
(35,'British Virgin Islands','','','','-- Sin asignar --','VG','','','','','','','','','','../../server/i18n/VG.png',1,'',0),
(36,'Brunei','','','','-- Sin asignar --','BN','','','','','','','','','','../../server/i18n/BN.png',1,'',0),
(37,'Bulgaria','','','','-- Sin asignar --','BG','','','','','','','','','','../../server/i18n/BG.png',1,'',0),
(38,'Burkina Faso','','','','-- Sin asignar --','BF','','','','','','','','','','../../server/i18n/BF.png',1,'',0),
(39,'Burundi','','','','-- Sin asignar --','BI','','','','','','','','','','../../server/i18n/BI.png',1,'',0),
(40,'Cambodia','','','','-- Sin asignar --','KH','','','','','','','','','','../../server/i18n/KH.png',1,'',0),
(41,'Cameroon','','','','-- Sin asignar --','CM','','','','','','','','','','../../server/i18n/CM.png',1,'',0),
(42,'Canada','','','','-- Sin asignar --','CA','','','','','','','','','','../../server/i18n/CA.png',1,'',0),
(43,'Canton and Enderbury Islands','','','','-- Sin asignar --','CT','','','','','','','','','','../../server/i18n/CT.png',1,'',0),
(44,'Cape Verde','','','','-- Sin asignar --','CV','','','','','','','','','','../../server/i18n/CV.png',1,'',0),
(45,'Cayman Islands','','','','-- Sin asignar --','KY','','','','','','','','','','../../server/i18n/KY.png',1,'',0),
(46,'Central African Republic','','','','-- Sin asignar --','CF','','','','','','','','','','../../server/i18n/CF.png',1,'',0),
(47,'Chad','','','','-- Sin asignar --','TD','','','','','','','','','','../../server/i18n/TD.png',1,'',0),
(48,'Chile','','','','-- Sin asignar --','CL','','','','','','','','','','../../server/i18n/CL.png',1,'',0),
(49,'China','','','','-- Sin asignar --','CN','','','','','','','','','','../../server/i18n/CN.png',1,'',0),
(50,'Christmas Island','','','','-- Sin asignar --','CX','','','','','','','','','','../../server/i18n/CX.png',1,'',0),
(51,'Cocos [Keeling] Islands','','','','-- Sin asignar --','CC','','','','','','','','','','../../server/i18n/CC.png',1,'',0),
(52,'Colombia','','','','-- Sin asignar --','CO','','','','','','','','','','../../server/i18n/CO.png',1,'',0),
(53,'Comoros','','','','-- Sin asignar --','KM','','','','','','','','','','../../server/i18n/KM.png',1,'',0),
(54,'Congo - Brazzaville','','','','-- Sin asignar --','CG','','','','','','','','','','../../server/i18n/CG.png',1,'',0),
(55,'Congo - Kinshasa','','','','-- Sin asignar --','CD','','','','','','','','','','../../server/i18n/CD.png',1,'',0),
(56,'Cook Islands','','','','-- Sin asignar --','CK','','','','','','','','','','../../server/i18n/CK.png',1,'',0),
(57,'Costa Rica','','','','-- Sin asignar --','CR','','','','','','','','','','../../server/i18n/CR.png',1,'',0),
(58,'Croatia','','','','-- Sin asignar --','HR','','','','','','','','','','../../server/i18n/HR.png',1,'',0),
(59,'Cuba','','','','-- Sin asignar --','CU','','','','','','','','','','../../server/i18n/CU.png',1,'',0),
(60,'Cyprus','','','','-- Sin asignar --','CY','','','','','','','','','','../../server/i18n/CY.png',1,'',0),
(61,'Czech Republic','','','','-- Sin asignar --','CZ','','','','','','','','','','../../server/i18n/CZ.png',1,'',0),
(62,'Côte d’Ivoire','','','','-- Sin asignar --','CI','','','','','','','','','','../../server/i18n/CI.png',1,'',0),
(63,'Denmark','','','','-- Sin asignar --','DK','','','','','','','','','','../../server/i18n/DK.png',1,'',0),
(64,'Djibouti','','','','-- Sin asignar --','DJ','','','','','','','','','','../../server/i18n/DJ.png',1,'',0),
(65,'Dominica','','','','-- Sin asignar --','DM','','','','','','','','','','../../server/i18n/DM.png',1,'',0),
(66,'Dominican Republic','','','','-- Sin asignar --','DO','','','','','','','','','','../../server/i18n/DO.png',1,'',0),
(67,'Dronning Maud Land','','','','-- Sin asignar --','NQ','','','','','','','','','','../../server/i18n/NQ.png',1,'',0),
(68,'East Germany','','','','-- Sin asignar --','DD','','','','','','','','','','../../server/i18n/DD.png',1,'',0),
(69,'Ecuador','','','','-- Sin asignar --','EC','','','','','','','','','','../../server/i18n/EC.png',1,'',0),
(70,'Egypt','','','','-- Sin asignar --','EG','','','','','','','','','','../../server/i18n/EG.png',1,'',0),
(71,'El Salvador','','','','-- Sin asignar --','SV','','','','','','','','','','../../server/i18n/SV.png',1,'',0),
(72,'Equatorial Guinea','','','','-- Sin asignar --','GQ','','','','','','','','','','../../server/i18n/GQ.png',1,'',0),
(73,'Eritrea','','','','-- Sin asignar --','ER','','','','','','','','','','../../server/i18n/ER.png',1,'',0),
(74,'Estonia','','','','-- Sin asignar --','EE','','','','','','','','','','../../server/i18n/EE.png',1,'',0),
(75,'Ethiopia','','','','-- Sin asignar --','ET','','','','','','','','','','../../server/i18n/ET.png',1,'',0),
(76,'Falkland Islands','','','','-- Sin asignar --','FK','','','','','','','','','','../../server/i18n/FK.png',1,'',0),
(77,'Faroe Islands','','','','-- Sin asignar --','FO','','','','','','','','','','../../server/i18n/FO.png',1,'',0),
(78,'Fiji','','','','-- Sin asignar --','FJ','','','','','','','','','','../../server/i18n/FJ.png',1,'',0),
(79,'Finland','','','','-- Sin asignar --','FI','','','','','','','','','','../../server/i18n/FI.png',1,'',0),
(80,'France','','','','-- Sin asignar --','FR','','','','','','','','','','../../server/i18n/FR.png',1,'',0),
(81,'French Guiana','','','','-- Sin asignar --','GF','','','','','','','','','','../../server/i18n/GF.png',1,'',0),
(82,'French Polynesia','','','','-- Sin asignar --','PF','','','','','','','','','','../../server/i18n/PF.png',1,'',0),
(83,'French Southern Territories','','','','-- Sin asignar --','TF','','','','','','','','','','../../server/i18n/TF.png',1,'',0),
(84,'French Southern and Antarctic Territories','','','','-- Sin asignar --','FQ','','','','','','','','','','../../server/i18n/FQ.png',1,'',0),
(85,'Gabon','','','','-- Sin asignar --','GA','','','','','','','','','','../../server/i18n/GA.png',1,'',0),
(86,'Gambia','','','','-- Sin asignar --','GM','','','','','','','','','','../../server/i18n/GM.png',1,'',0),
(87,'Georgia','','','','-- Sin asignar --','GE','','','','','','','','','','../../server/i18n/GE.png',1,'',0),
(88,'Germany','','','','-- Sin asignar --','DE','','','','','','','','','','../../server/i18n/DE.png',1,'',0),
(89,'Ghana','','','','-- Sin asignar --','GH','','','','','','','','','','../../server/i18n/GH.png',1,'',0),
(90,'Gibraltar','','','','-- Sin asignar --','GI','','','','','','','','','','../../server/i18n/GI.png',1,'',0),
(91,'Greece','','','','-- Sin asignar --','GR','','','','','','','','','','../../server/i18n/GR.png',1,'',0),
(92,'Greenland','','','','-- Sin asignar --','GL','','','','','','','','','','../../server/i18n/GL.png',1,'',0),
(93,'Grenada','','','','-- Sin asignar --','GD','','','','','','','','','','../../server/i18n/GD.png',1,'',0),
(94,'Guadeloupe','','','','-- Sin asignar --','GP','','','','','','','','','','../../server/i18n/GP.png',1,'',0),
(95,'Guam','','','','-- Sin asignar --','GU','','','','','','','','','','../../server/i18n/GU.png',1,'',0),
(96,'Guatemala','','','','-- Sin asignar --','GT','','','','','','','','','','../../server/i18n/GT.png',1,'',0),
(97,'Guernsey','','','','-- Sin asignar --','GG','','','','','','','','','','../../server/i18n/GG.png',1,'',0),
(98,'Guinea','','','','-- Sin asignar --','GN','','','','','','','','','','../../server/i18n/GN.png',1,'',0),
(99,'Guinea-Bissau','','','','-- Sin asignar --','GW','','','','','','','','','','../../server/i18n/GW.png',1,'',0),
(100,'Guyana','','','','-- Sin asignar --','GY','','','','','','','','','','../../server/i18n/GY.png',1,'',0),
(101,'Haiti','','','','-- Sin asignar --','HT','','','','','','','','','','../../server/i18n/HT.png',1,'',0),
(102,'Heard Island and McDonald Islands','','','','-- Sin asignar --','HM','','','','','','','','','','../../server/i18n/HM.png',1,'',0),
(103,'Honduras','','','','-- Sin asignar --','HN','','','','','','','','','','../../server/i18n/HN.png',1,'',0),
(104,'Hong Kong SAR China','','','','-- Sin asignar --','HK','','','','','','','','','','../../server/i18n/HK.png',1,'',0),
(105,'Hungary','','','','-- Sin asignar --','HU','','','','','','','','','','../../server/i18n/HU.png',1,'',0),
(106,'Iceland','','','','-- Sin asignar --','IS','','','','','','','','','','../../server/i18n/IS.png',1,'',0),
(107,'India','','','','-- Sin asignar --','IN','','','','','','','','','','../../server/i18n/IN.png',1,'',0),
(108,'Indonesia','','','','-- Sin asignar --','ID','','','','','','','','','','../../server/i18n/ID.png',1,'',0),
(109,'Iran','','','','-- Sin asignar --','IR','','','','','','','','','','../../server/i18n/IR.png',1,'',0),
(110,'Iraq','','','','-- Sin asignar --','IQ','','','','','','','','','','../../server/i18n/IQ.png',1,'',0),
(111,'Ireland','','','','-- Sin asignar --','IE','','','','','','','','','','../../server/i18n/IE.png',1,'',0),
(112,'Isle of Man','','','','-- Sin asignar --','IM','','','','','','','','','','../../server/i18n/IM.png',1,'',0),
(113,'Israel','','','','-- Sin asignar --','IL','','','','','','','','','','../../server/i18n/IL.png',1,'',0),
(114,'Italy','','','','-- Sin asignar --','IT','','','','','','','','','','../../server/i18n/IT.png',1,'',0),
(115,'Jamaica','','','','-- Sin asignar --','JM','','','','','','','','','','../../server/i18n/JM.png',1,'',0),
(116,'Japan','','','','-- Sin asignar --','JP','','','','','','','','','','../../server/i18n/JP.png',1,'',0),
(117,'Jersey','','','','-- Sin asignar --','JE','','','','','','','','','','../../server/i18n/JE.png',1,'',0),
(118,'Johnston Island','','','','-- Sin asignar --','JT','','','','','','','','','','../../server/i18n/JT.png',1,'',0),
(119,'Jordan','','','','-- Sin asignar --','JO','','','','','','','','','','../../server/i18n/JO.png',1,'',0),
(120,'Kazakhstan','','','','-- Sin asignar --','KZ','','','','','','','','','','../../server/i18n/KZ.png',1,'',0),
(121,'Kenya','','','','-- Sin asignar --','KE','','','','','','','','','','../../server/i18n/KE.png',1,'',0),
(122,'Kiribati','','','','-- Sin asignar --','KI','','','','','','','','','','../../server/i18n/KI.png',1,'',0),
(123,'Kuwait','','','','-- Sin asignar --','KW','','','','','','','','','','../../server/i18n/KW.png',1,'',0),
(124,'Kyrgyzstan','','','','-- Sin asignar --','KG','','','','','','','','','','../../server/i18n/KG.png',1,'',0),
(125,'Laos','','','','-- Sin asignar --','LA','','','','','','','','','','../../server/i18n/LA.png',1,'',0),
(126,'Latvia','','','','-- Sin asignar --','LV','','','','','','','','','','../../server/i18n/LV.png',1,'',0),
(127,'Lebanon','','','','-- Sin asignar --','LB','','','','','','','','','','../../server/i18n/LB.png',1,'',0),
(128,'Lesotho','','','','-- Sin asignar --','LS','','','','','','','','','','../../server/i18n/LS.png',1,'',0),
(129,'Liberia','','','','-- Sin asignar --','LR','','','','','','','','','','../../server/i18n/LR.png',1,'',0),
(130,'Libya','','','','-- Sin asignar --','LY','','','','','','','','','','../../server/i18n/LY.png',1,'',0),
(131,'Liechtenstein','','','','-- Sin asignar --','LI','','','','','','','','','','../../server/i18n/LI.png',1,'',0),
(132,'Lithuania','','','','-- Sin asignar --','LT','','','','','','','','','','../../server/i18n/LT.png',1,'',0),
(133,'Luxembourg','','','','-- Sin asignar --','LU','','','','','','','','','','../../server/i18n/LU.png',1,'',0),
(134,'Macau SAR China','','','','-- Sin asignar --','MO','','','','','','','','','','../../server/i18n/MO.png',1,'',0),
(135,'Macedonia','','','','-- Sin asignar --','MK','','','','','','','','','','../../server/i18n/MK.png',1,'',0),
(136,'Madagascar','','','','-- Sin asignar --','MG','','','','','','','','','','../../server/i18n/MG.png',1,'',0),
(137,'Malawi','','','','-- Sin asignar --','MW','','','','','','','','','','../../server/i18n/MW.png',1,'',0),
(138,'Malaysia','','','','-- Sin asignar --','MY','','','','','','','','','','../../server/i18n/MY.png',1,'',0),
(139,'Maldives','','','','-- Sin asignar --','MV','','','','','','','','','','../../server/i18n/MV.png',1,'',0),
(140,'Mali','','','','-- Sin asignar --','ML','','','','','','','','','','../../server/i18n/ML.png',1,'',0),
(141,'Malta','','','','-- Sin asignar --','MT','','','','','','','','','','../../server/i18n/MT.png',1,'',0),
(142,'Marshall Islands','','','','-- Sin asignar --','MH','','','','','','','','','','../../server/i18n/MH.png',1,'',0),
(143,'Martinique','','','','-- Sin asignar --','MQ','','','','','','','','','','../../server/i18n/MQ.png',1,'',0),
(144,'Mauritania','','','','-- Sin asignar --','MR','','','','','','','','','','../../server/i18n/MR.png',1,'',0),
(145,'Mauritius','','','','-- Sin asignar --','MU','','','','','','','','','','../../server/i18n/MU.png',1,'',0),
(146,'Mayotte','','','','-- Sin asignar --','YT','','','','','','','','','','../../server/i18n/YT.png',1,'',0),
(147,'Metropolitan France','','','','-- Sin asignar --','FX','','','','','','','','','','../../server/i18n/FX.png',1,'',0),
(148,'Mexico','','','','-- Sin asignar --','MX','','','','','','','','','','../../server/i18n/MX.png',1,'',0),
(149,'Micronesia','','','','-- Sin asignar --','FM','','','','','','','','','','../../server/i18n/FM.png',1,'',0),
(150,'Midway Islands','','','','-- Sin asignar --','MI','','','','','','','','','','../../server/i18n/MI.png',1,'',0),
(151,'Moldova','','','','-- Sin asignar --','MD','','','','','','','','','','../../server/i18n/MD.png',1,'',0),
(152,'Monaco','','','','-- Sin asignar --','MC','','','','','','','','','','../../server/i18n/MC.png',1,'',0),
(153,'Mongolia','','','','-- Sin asignar --','MN','','','','','','','','','','../../server/i18n/MN.png',1,'',0),
(154,'Montenegro','','','','-- Sin asignar --','ME','','','','','','','','','','../../server/i18n/ME.png',1,'',0),
(155,'Montserrat','','','','-- Sin asignar --','MS','','','','','','','','','','../../server/i18n/MS.png',1,'',0),
(156,'Morocco','','','','-- Sin asignar --','MA','','','','','','','','','','../../server/i18n/MA.png',1,'',0),
(157,'Mozambique','','','','-- Sin asignar --','MZ','','','','','','','','','','../../server/i18n/MZ.png',1,'',0),
(158,'Myanmar [Burma]','','','','-- Sin asignar --','MM','','','','','','','','','','../../server/i18n/MM.png',1,'',0),
(159,'Namibia','','','','-- Sin asignar --','NA','','','','','','','','','','../../server/i18n/NA.png',1,'',0),
(160,'Nauru','','','','-- Sin asignar --','NR','','','','','','','','','','../../server/i18n/NR.png',1,'',0),
(161,'Nepal','','','','-- Sin asignar --','NP','','','','','','','','','','../../server/i18n/NP.png',1,'',0),
(162,'Netherlands','','','','-- Sin asignar --','NL','','','','','','','','','','../../server/i18n/NL.png',1,'',0),
(163,'Netherlands Antilles','','','','-- Sin asignar --','AN','','','','','','','','','','../../server/i18n/AN.png',1,'',0),
(164,'Neutral Zone','','','','-- Sin asignar --','NT','','','','','','','','','','../../server/i18n/NT.png',1,'',0),
(165,'New Caledonia','','','','-- Sin asignar --','NC','','','','','','','','','','../../server/i18n/NC.png',1,'',0),
(166,'New Zealand','','','','-- Sin asignar --','NZ','','','','','','','','','','../../server/i18n/NZ.png',1,'',0),
(167,'Nicaragua','','','','-- Sin asignar --','NI','','','','','','','','','','../../server/i18n/NI.png',1,'',0),
(168,'Niger','','','','-- Sin asignar --','NE','','','','','','','','','','../../server/i18n/NE.png',1,'',0),
(169,'Nigeria','','','','-- Sin asignar --','NG','','','','','','','','','','../../server/i18n/NG.png',1,'',0),
(170,'Niue','','','','-- Sin asignar --','NU','','','','','','','','','','../../server/i18n/NU.png',1,'',0),
(171,'Norfolk Island','','','','-- Sin asignar --','NF','','','','','','','','','','../../server/i18n/NF.png',1,'',0),
(172,'North Korea','','','','-- Sin asignar --','KP','','','','','','','','','','../../server/i18n/KP.png',1,'',0),
(173,'North Vietnam','','','','-- Sin asignar --','VD','','','','','','','','','','../../server/i18n/VD.png',1,'',0),
(174,'Northern Mariana Islands','','','','-- Sin asignar --','MP','','','','','','','','','','../../server/i18n/MP.png',1,'',0),
(175,'Norway','','','','-- Sin asignar --','NO','','','','','','','','','','../../server/i18n/NO.png',1,'',0),
(176,'Oman','','','','-- Sin asignar --','OM','','','','','','','','','','../../server/i18n/OM.png',1,'',0),
(177,'Pacific Islands Trust Territory','','','','-- Sin asignar --','PC','','','','','','','','','','../../server/i18n/PC.png',1,'',0),
(178,'Pakistan','','','','-- Sin asignar --','PK','','','','','','','','','','../../server/i18n/PK.png',1,'',0),
(179,'Palau','','','','-- Sin asignar --','PW','','','','','','','','','','../../server/i18n/PW.png',1,'',0),
(180,'Palestinian Territories','','','','-- Sin asignar --','PS','','','','','','','','','','../../server/i18n/PS.png',1,'',0),
(181,'Panama','','','','-- Sin asignar --','PA','','','','','','','','','','../../server/i18n/PA.png',1,'',0),
(182,'Panama Canal Zone','','','','-- Sin asignar --','PZ','','','','','','','','','','../../server/i18n/PZ.png',1,'',0),
(183,'Papua New Guinea','','','','-- Sin asignar --','PG','','','','','','','','','','../../server/i18n/PG.png',1,'',0),
(184,'Paraguay','','','','-- Sin asignar --','PY','','','','','','','','','','../../server/i18n/PY.png',1,'',0),
(185,'People\'s Democratic Republic of Yemen','','','','-- Sin asignar --','YD','','','','','','','','','','../../server/i18n/YD.png',1,'',0),
(186,'Peru','','','','-- Sin asignar --','PE','','','','','','','','','','../../server/i18n/PE.png',1,'',0),
(187,'Philippines','','','','-- Sin asignar --','PH','','','','','','','','','','../../server/i18n/PH.png',1,'',0),
(188,'Pitcairn Islands','','','','-- Sin asignar --','PN','','','','','','','','','','../../server/i18n/PN.png',1,'',0),
(189,'Poland','','','','-- Sin asignar --','PL','','','','','','','','','','../../server/i18n/PL.png',1,'',0),
(190,'Portugal','','','','-- Sin asignar --','PT','','','','','','','','','','../../server/i18n/PT.png',1,'',0),
(191,'Puerto Rico','','','','-- Sin asignar --','PR','','','','','','','','','','../../server/i18n/PR.png',1,'',0),
(192,'Qatar','','','','-- Sin asignar --','QA','','','','','','','','','','../../server/i18n/QA.png',1,'',0),
(193,'Romania','','','','-- Sin asignar --','RO','','','','','','','','','','../../server/i18n/RO.png',1,'',0),
(194,'Russia','','','','-- Sin asignar --','RU','','','','','','','','','','../../server/i18n/RU.png',1,'',0),
(195,'Rwanda','','','','-- Sin asignar --','RW','','','','','','','','','','../../server/i18n/RW.png',1,'',0),
(196,'Réunion','','','','-- Sin asignar --','RE','','','','','','','','','','../../server/i18n/RE.png',1,'',0),
(197,'Saint Barthélemy','','','','-- Sin asignar --','BL','','','','','','','','','','../../server/i18n/BL.png',1,'',0),
(198,'Saint Helena','','','','-- Sin asignar --','SH','','','','','','','','','','../../server/i18n/SH.png',1,'',0),
(199,'Saint Kitts and Nevis','','','','-- Sin asignar --','KN','','','','','','','','','','../../server/i18n/KN.png',1,'',0),
(200,'Saint Lucia','','','','-- Sin asignar --','LC','','','','','','','','','','../../server/i18n/LC.png',1,'',0),
(201,'Saint Martin','','','','-- Sin asignar --','MF','','','','','','','','','','../../server/i18n/MF.png',1,'',0),
(202,'Saint Pierre and Miquelon','','','','-- Sin asignar --','PM','','','','','','','','','','../../server/i18n/PM.png',1,'',0),
(203,'Saint Vincent and the Grenadines','','','','-- Sin asignar --','VC','','','','','','','','','','../../server/i18n/VC.png',1,'',0),
(204,'Samoa','','','','-- Sin asignar --','WS','','','','','','','','','','../../server/i18n/WS.png',1,'',0),
(205,'San Marino','','','','-- Sin asignar --','SM','','','','','','','','','','../../server/i18n/SM.png',1,'',0),
(206,'Saudi Arabia','','','','-- Sin asignar --','SA','','','','','','','','','','../../server/i18n/SA.png',1,'',0),
(207,'Senegal','','','','-- Sin asignar --','SN','','','','','','','','','','../../server/i18n/SN.png',1,'',0),
(208,'Serbia','','','','-- Sin asignar --','RS','','','','','','','','','','../../server/i18n/RS.png',1,'',0),
(209,'Serbia and Montenegro','','','','-- Sin asignar --','CS','','','','','','','','','','../../server/i18n/CS.png',1,'',0),
(210,'Seychelles','','','','-- Sin asignar --','SC','','','','','','','','','','../../server/i18n/SC.png',1,'',0),
(211,'Sierra Leone','','','','-- Sin asignar --','SL','','','','','','','','','','../../server/i18n/SL.png',1,'',0),
(212,'Singapore','','','','-- Sin asignar --','SG','','','','','','','','','','../../server/i18n/SG.png',1,'',0),
(213,'Slovakia','','','','-- Sin asignar --','SK','','','','','','','','','','../../server/i18n/SK.png',1,'',0),
(214,'Slovenia','','','','-- Sin asignar --','SI','','','','','','','','','','../../server/i18n/SI.png',1,'',0),
(215,'Solomon Islands','','','','-- Sin asignar --','SB','','','','','','','','','','../../server/i18n/SB.png',1,'',0),
(216,'Somalia','','','','-- Sin asignar --','SO','','','','','','','','','','../../server/i18n/SO.png',1,'',0),
(217,'South Africa','','','','-- Sin asignar --','ZA','','','','','','','','','','../../server/i18n/ZA.png',1,'',0),
(218,'South Georgia and the South Sandwich Islands','','','','-- Sin asignar --','GS','','','','','','','','','','../../server/i18n/GS.png',1,'',0),
(219,'South Korea','','','','-- Sin asignar --','KR','','','','','','','','','','../../server/i18n/KR.png',1,'',0),
(220,'Spain','','','','-- Sin asignar --','ES','','','','','','','','','','../../server/i18n/ES.png',1,'',0),
(221,'Sri Lanka','','','','-- Sin asignar --','LK','','','','','','','','','','../../server/i18n/LK.png',1,'',0),
(222,'Sudan','','','','-- Sin asignar --','SD','','','','','','','','','','../../server/i18n/SD.png',1,'',0),
(223,'Suriname','','','','-- Sin asignar --','SR','','','','','','','','','','../../server/i18n/SR.png',1,'',0),
(224,'Svalbard and Jan Mayen','','','','-- Sin asignar --','SJ','','','','','','','','','','../../server/i18n/SJ.png',1,'',0),
(225,'Swaziland','','','','-- Sin asignar --','SZ','','','','','','','','','','../../server/i18n/SZ.png',1,'',0),
(226,'Sweden','','','','-- Sin asignar --','SE','','','','','','','','','','../../server/i18n/SE.png',1,'',0),
(227,'Switzerland','','','','-- Sin asignar --','CH','','','','','','','','','','../../server/i18n/CH.png',1,'',0),
(228,'Syria','','','','-- Sin asignar --','SY','','','','','','','','','','../../server/i18n/SY.png',1,'',0),
(229,'São Tomé and Príncipe','','','','-- Sin asignar --','ST','','','','','','','','','','../../server/i18n/ST.png',1,'',0),
(230,'Taiwan','','','','-- Sin asignar --','TW','','','','','','','','','','../../server/i18n/TW.png',1,'',0),
(231,'Tajikistan','','','','-- Sin asignar --','TJ','','','','','','','','','','../../server/i18n/TJ.png',1,'',0),
(232,'Tanzania','','','','-- Sin asignar --','TZ','','','','','','','','','','../../server/i18n/TZ.png',1,'',0),
(233,'Thailand','','','','-- Sin asignar --','TH','','','','','','','','','','../../server/i18n/TH.png',1,'',0),
(234,'Timor-Leste','','','','-- Sin asignar --','TL','','','','','','','','','','../../server/i18n/TL.png',1,'',0),
(235,'Togo','','','','-- Sin asignar --','TG','','','','','','','','','','../../server/i18n/TG.png',1,'',0),
(236,'Tokelau','','','','-- Sin asignar --','TK','','','','','','','','','','../../server/i18n/TK.png',1,'',0),
(237,'Tonga','','','','-- Sin asignar --','TO','','','','','','','','','','../../server/i18n/TO.png',1,'',0),
(238,'Trinidad and Tobago','','','','-- Sin asignar --','TT','','','','','','','','','','../../server/i18n/TT.png',1,'',0),
(239,'Tunisia','','','','-- Sin asignar --','TN','','','','','','','','','','../../server/i18n/TN.png',1,'',0),
(240,'Turkey','','','','-- Sin asignar --','TR','','','','','','','','','','../../server/i18n/TR.png',1,'',0),
(241,'Turkmenistan','','','','-- Sin asignar --','TM','','','','','','','','','','../../server/i18n/TM.png',1,'',0),
(242,'Turks and Caicos Islands','','','','-- Sin asignar --','TC','','','','','','','','','','../../server/i18n/TC.png',1,'',0),
(243,'Tuvalu','','','','-- Sin asignar --','TV','','','','','','','','','','../../server/i18n/TV.png',1,'',0),
(244,'U.S. Minor Outlying Islands','','','','-- Sin asignar --','UM','','','','','','','','','','../../server/i18n/UM.png',1,'',0),
(245,'U.S. Miscellaneous Pacific Islands','','','','-- Sin asignar --','PU','','','','','','','','','','../../server/i18n/PU.png',1,'',0),
(246,'U.S. Virgin Islands','','','','-- Sin asignar --','VI','','','','','','','','','','../../server/i18n/VI.png',1,'',0),
(247,'Uganda','','','','-- Sin asignar --','UG','','','','','','','','','','../../server/i18n/UG.png',1,'',0),
(248,'Ukraine','','','','-- Sin asignar --','UA','','','','','','','','','','../../server/i18n/UA.png',1,'',0),
(249,'Union of Soviet Socialist Republics','','','','-- Sin asignar --','SU','','','','','','','','','','../../server/i18n/SU.png',1,'',0),
(250,'United Arab Emirates','','','','-- Sin asignar --','AE','','','','','','','','','','../../server/i18n/AE.png',1,'',0),
(251,'Great Britain','','','','-- Sin asignar --','GB','','','','','','','','','','../../server/i18n/GB.png',1,'',0),
(252,'United States','','','','-- Sin asignar --','US','','','','','','','','','','../../server/i18n/US.png',1,'',0),
(253,'Unknown or Invalid Region','','','','-- Sin asignar --','ZZ','','','','','','','','','','../../server/i18n/ZZ.png',1,'',0),
(254,'Uruguay','','','','-- Sin asignar --','UY','','','','','','','','','','../../server/i18n/UY.png',1,'',0),
(255,'Uzbekistan','','','','-- Sin asignar --','UZ','','','','','','','','','','../../server/i18n/UZ.png',1,'',0),
(256,'Vanuatu','','','','-- Sin asignar --','VU','','','','','','','','','','../../server/i18n/VU.png',1,'',0),
(257,'Vatican City','','','','-- Sin asignar --','VA','','','','','','','','','','../../server/i18n/VA.png',1,'',0),
(258,'Venezuela','','','','-- Sin asignar --','VE','','','','','','','','','','../../server/i18n/VE.png',1,'',0),
(259,'Vietnam','','','','-- Sin asignar --','VN','','','','','','','','','','../../server/i18n/VN.png',1,'',0),
(260,'Wake Island','','','','-- Sin asignar --','WK','','','','','','','','','','../../server/i18n/WK.png',1,'',0),
(261,'Wallis and Futuna','','','','-- Sin asignar --','WF','','','','','','','','','','../../server/i18n/WF.png',1,'',0),
(262,'Western Sahara','','','','-- Sin asignar --','EH','','','','','','','','','','../../server/i18n/EH.png',1,'',0),
(263,'Yemen','','','','-- Sin asignar --','YE','','','','','','','','','','../../server/i18n/YE.png',1,'',0),
(264,'Zambia','','','','-- Sin asignar --','ZM','','','','','','','','','','../../server/i18n/ZM.png',1,'',0),
(265,'Zimbabwe','','','','-- Sin asignar --','ZW','','','','','','','','','','../../server/i18n/ZW.png',1,'',0),
(266,'Åland Islands','','','','-- Sin asignar --','AX','','','','','','','','','','../../server/i18n/AX.png',1,'',0);
